### ISSUE TITLE
0.7.0 uses Guava API removed in Guava 21.0

### ISSUE THREAD

**Issue by pcarrier** [killbilling/recurly-java-library#174]
```
java.lang.NoSuchMethodError: com.google.common.base.Objects.firstNonNull(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        at com.ning.billing.recurly.RecurlyClient.buildUserAgent(RecurlyClient.java:1499)
        at com.ning.billing.recurly.RecurlyClient.<init>(RecurlyClient.java:140)
        at com.ning.billing.recurly.RecurlyClient.<init>(RecurlyClient.java:133)
        at com.ning.billing.recurly.RecurlyClient.<init>(RecurlyClient.java:129)
```

**Comment by pcarrier** [comment]
`Objects.firstNonNull` was replaced with `MoreObjects.firstNonNull`.

**Comment by pcarrier** [comment]
Already solved through https://github.com/killbilling/recurly-java-library/pull/173 ; down to waiting for a new release :)

**Comment by pierre** [comment]
@pcarrier I'll create a new release once https://github.com/killbilling/recurly-java-library/pull/172#issuecomment-274265148 is fixed.
