### ISSUE TITLE
doGET does not distinguish between "not found" and timeout.

### ISSUE THREAD

**Issue by geoffcallender** [killbilling/recurly-java-library#185]
If the RecurlyClient suffers timeout, it logs "Execution error" and returns null. To the caller, it's indistinguishable from "not found". For example, when I tried to find an Account...  

```
	Account account = getRecurlyClient().getAccount(accountCode);
```

...and it timed out, a null account was returned rather than an exception. The following was logged (using version 0.8.0)...  

```
ERROR [Timer-7] (RecurlyClient.java:1483) - Execution error
java.util.concurrent.ExecutionException: java.net.ConnectException: connection timed out: goxpro-dev.recurly.com/104.16.113.53:443
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:232)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:151)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:159)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:142)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:83)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: connection timed out: goxpro-dev.recurly.com/104.16.113.53:443
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:147)
	... 13 more
Caused by: org.jboss.netty.channel.ConnectTimeoutException: connection timed out: goxpro-dev.recurly.com/104.16.113.53:443
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:139)
	... 8 more
```

...because RecurlyClient logged the exception but returned null...

```
    private <T> T callRecurlySafeXmlContent(final AsyncHttpClient.BoundRequestBuilder builder, @Nullable final Class<T> clazz) {
        try {
            return callRecurlyXmlContent(builder, clazz);
        } catch (IOException e) {
            log.warn("Error while calling Recurly", e);
            return null;
        } catch (ExecutionException e) {
            // Extract the errors exception, if any
            if (e.getCause() != null &&
                e.getCause().getCause() != null &&
                e.getCause().getCause() instanceof TransactionErrorException) {
                throw (TransactionErrorException) e.getCause().getCause();
            } else if (e.getCause() != null &&
                       e.getCause() instanceof TransactionErrorException) {
                // See https://github.com/killbilling/recurly-java-library/issues/16
                throw (TransactionErrorException) e.getCause();
            }
            log.error("Execution error", e);    // <<<<<<<< Here
            return null;    // <<<<<<<< And here
        } catch (InterruptedException e) {
            log.error("Interrupted while calling Recurly", e);
            return null;
        }
    }
```

**Comment by bhelx** [comment]
@geoffcallender I ran this code and got a successful 404:

```java
        try {
            Account account = recurlyClient.getAccount("idontexistatall");
        } catch (RecurlyAPIException e) {
            System.out.println(e.getRecurlyError().getSymbol()); // not_found
        }
```

It does seem to me like the expected behavior of a timeout would be an exception but perhaps `callRecurlySafeXmlContent` was designed that way for a reason.

@pierre do you have any input on that? Perhaps we can catch a Timeout exception of some kind of wrap it in a Recurly error.

**Comment by pierre** [comment]
> do you have any input on that? Perhaps we can catch a Timeout exception of some kind and wrap it in a Recurly error.

It was indeed originally designed that way (`null` returned in case of system error, `RecurlyAPIException` in case of server-side error), but it's true that it can be confusing if one wants to programmatically handle these exceptions.

We could change this and throw a new exception (probably runtime, to avoid signature changes) instead, wrapping `IOException`, `ExecutionException` and `InterruptedException`?

**Comment by geoffcallender** [comment]
I stand corrected. If not found, then it does indeed return a RecurlyAPIException wrapping a 404. However, I like pierre's thought that everything other than success should throw an exception instead of returning null.

**Comment by bhelx** [comment]
@geoffcallender I think I could go either way on the 404 interface. The way I see it, there are 2 ways people use 404s in our API.

  1. You are sending the request knowing that the account may or may not exist. In this case, it would make sense to return a null because an account not existing is not an "exceptional" case. It's something you expect will happen.
  2. You have a Recurly account code (collected or created on signup) in your database and you are using that to look up an account (so you can add a charge for example). In this case you expect the account to be there every time so a 404 would be an exceptional circumstance. 

For now we'll probably just leave it as it is because I like to avoid interface changes if at all possible.  If you want to clean up your code for your case, I'd maybe suggest writing your own `find*` wrappers around the `get*` methods. You might even be able to extend RecurlyClient and have your own flavor (although I've never tried it).

As for the Timeout, I definitely think that should be an exception so I'm going to look this week at getting that working. I'm going to think a little about how this will work. I do think we need to be able to programatically handle timeouts for the sake of retry logic.

**Comment by geoffcallender** [comment]
While you're there, another error to handle is ConnectException. I get these from time to time while testing, and they're temporary. Currently, RecurlyClient returns null.

 INFO [1894902783@qtp-2138564891-5] (RecurlyClient.java:1409) - Msg to Recurly API [GET] :: URL : https://goxpro-dev.recurly.com:443/v2/accounts/vDAI94MiRX/invoices?per_page=20
ERROR [1894902783@qtp-2138564891-5] (RecurlyClient.java:1512) - Execution error
java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: goxpro-dev.recurly.com/104.16.113.53:443
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:232)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:151)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:159)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: goxpro-dev.recurly.com/104.16.113.53:443
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:147)
	... 13 more
Caused by: java.net.ConnectException: Connection refused: goxpro-dev.recurly.com/104.16.113.53:443
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	... 8 more

**Comment by aaron-suarez** [comment]
@geoffcallender  Both the `Connection refused` as well as the `connection timed out` messages come from an instance of `java.net.ConnectException`. The PR I just opened should take care of both.
