### ISSUE TITLE
Unable to open recurly connection.

### ISSUE THREAD

**Issue by avinashmadireddy** [killbilling/recurly-java-library#200]
Caused by: java.lang.ClassNotFoundException: sun.security.util.HostnameChecker from [Module "deployment.seqnc-engine.war:main" from Service Module Loader]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:468)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:456)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:120)
        at com.ning.http.util.ProxyHostnameChecker.getHostnameChecker(ProxyHostnameChecker.java:37)

**Comment by bhelx** [comment]
@avinashmadireddy I'm not seeing anything from this library in the stack trace. What makes you think this library is responsible?

**Comment by bhelx** [comment]
Sorry, I see the `com.ning.http.util.ProxyHostnameChecker.getHostnameChecker` now.

@pierre any ideas on what could be causing this? Perhaps some kind of dependency problem?

**Comment by avinashmadireddy** [comment]
Yes, you are right. It's a dependency issue at my end. It's taken care.
Thanks.
