### ISSUE TITLE
UnmarshalException because updated_account_notification not handled

### ISSUE THREAD

**Issue by geoffcallender** [killbilling/recurly-java-library#219]
In 0.11.0, my web hook is receiving a POST that fails due to:  

```
RESTEASY002005: Failed executing POST /recurly: org.jboss.resteasy.plugins.providers.jaxb.JAXBUnmarshalException: javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"updated_account_notification"). Expected elements are <{}account>,<{}billing_info_updated_notification>,<{}canceled_account_notification>,<{}canceled_subscription_notification>,<{}closed_invoice_notification>,<{}expired_subscription_notification>,<{}failed_payment_notification>,<{}invoice>,<{}new_account_notification>,<{}new_invoice_notification>,<{}new_subscription_notification>,<{}past_due_invoice_notification>,<{}reactivated_account_notification>,<{}renewed_subscription_notification>,<{}subscription>,<{}successful_payment_notification>,<{}successful_refund_notification>,<{}transaction>,<{}updated_subscription_notification>,<{}void_payment_notification>
```

Are we missing a class UpdatedAccountNotification which is annotated with @XmlElement(name = "updated_account_notification")?

**Comment by pierre** [comment]
Fixed in 0.13.1.

**Comment by geoffcallender** [comment]
Weird. With 0.13.1 I'm still getting this:

```
ERROR [qtp1684015092-16] (ExceptionHandler.java:151) - RESTEASY002005: Failed executing POST /recurly
org.jboss.resteasy.plugins.providers.jaxb.JAXBUnmarshalException: javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"updated_account_notification"). Expected elements are <{}account>,<{}billing_info_updated_notification>,<{}canceled_account_notification>,<{}canceled_subscription_notification>,<{}closed_invoice_notification>,<{}expired_subscription_notification>,<{}failed_payment_notification>,<{}invoice>,<{}new_account_notification>,<{}new_invoice_notification>,<{}new_subscription_notification>,<{}past_due_invoice_notification>,<{}reactivated_account_notification>,<{}renewed_subscription_notification>,<{}subscription>,<{}successful_payment_notification>,<{}successful_refund_notification>,<{}transaction>,<{}updated_subscription_notification>,<{}void_payment_notification>
	at org.jboss.resteasy.plugins.providers.jaxb.AbstractJAXBProvider.readFrom(AbstractJAXBProvider.java:132)
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:61)
	at org.jboss.resteasy.core.interception.ServerReaderInterceptorContext.readFrom(ServerReaderInterceptorContext.java:60)
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:53)
	at org.jboss.resteasy.plugins.interceptors.encoding.GZIPDecodingInterceptor.aroundReadFrom(GZIPDecodingInterceptor.java:59)
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:55)
	at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:151)
	at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:91)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:114)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.tynamo.resteasy.ResteasyRequestFilter.service(ResteasyRequestFilter.java:98)
	at $HttpServletRequestFilter_626d4c81894f.service(Unknown Source)
	at $HttpServletRequestHandler_626d4c818953.service(Unknown Source)
	at org.apache.tapestry5.internal.services.IgnoredPathsFilter.service(IgnoredPathsFilter.java:62)
	at $HttpServletRequestFilter_626d4c81894d.service(Unknown Source)
	at $HttpServletRequestHandler_626d4c818953.service(Unknown Source)
	at org.apache.tapestry5.modules.TapestryModule$1.service(TapestryModule.java:796)
	at $HttpServletRequestHandler_626d4c818953.service(Unknown Source)
	at com.goxpro.xpro.web.recurly.services.RecurlyWebhookProtectionFilter.service(RecurlyWebhookProtectionFilter.java:122)
	at $HttpServletRequestHandler_626d4c818953.service(Unknown Source)
	at com.goxpro.xpro.web.domicilgym.services.DomicilGymWebhookProtectionFilter.service(DomicilGymWebhookProtectionFilter.java:118)
	at $HttpServletRequestHandler_626d4c818953.service(Unknown Source)
	at com.goxpro.xpro.web.clickfunnels.services.ClickfunnelsWebhookProtectionFilter.service(ClickfunnelsWebhookProtectionFilter.java:90)
	at $HttpServletRequestHandler_626d4c818953.service(Unknown Source)
	at $HttpServletRequestHandler_626d4c81894b.service(Unknown Source)
	at org.apache.tapestry5.TapestryFilter.doFilter(TapestryFilter.java:166)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"updated_account_notification"). Expected elements are <{}account>,<{}billing_info_updated_notification>,<{}canceled_account_notification>,<{}canceled_subscription_notification>,<{}closed_invoice_notification>,<{}expired_subscription_notification>,<{}failed_payment_notification>,<{}invoice>,<{}new_account_notification>,<{}new_invoice_notification>,<{}new_subscription_notification>,<{}past_due_invoice_notification>,<{}reactivated_account_notification>,<{}renewed_subscription_notification>,<{}subscription>,<{}successful_payment_notification>,<{}successful_refund_notification>,<{}transaction>,<{}updated_subscription_notification>,<{}void_payment_notification>
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:662)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:258)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:253)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:120)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1063)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:498)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:480)
	at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:150)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:380)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:619)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3129)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:880)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:258)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:229)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:140)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:123)
	at org.jboss.resteasy.plugins.providers.jaxb.SecureUnmarshaller.unmarshal(SecureUnmarshaller.java:164)
	at org.jboss.resteasy.plugins.providers.jaxb.SecureUnmarshaller.unmarshal(SecureUnmarshaller.java:140)
	at org.jboss.resteasy.plugins.providers.jaxb.AbstractJAXBProvider.processWithSecureProcessing(AbstractJAXBProvider.java:295)
	at org.jboss.resteasy.plugins.providers.jaxb.AbstractJAXBProvider.readFrom(AbstractJAXBProvider.java:114)
	... 48 more
```
