### ISSUE TITLE
Exception "TokenBuffer cannot be cast to ToXmlGenerator" when parsing an invoice to a JsonNode

### ISSUE THREAD

**Issue by m-revetria** [killbilling/recurly-java-library#236]
Hi,
I'm seeing this exception when trying to parse an `Invoice` back to `JsonNode`. For this I'm using `RecurlyObject.newXmlMapper`. See the snippet below:

```java
Invoice invoice = fetchSomeInvoice();
XmlMapper xmlMapper = RecurlyObject.newXmlMapper();
JsonNode node = xmlMapper.valueToTree(invoice); // <- This line is throwing the exception
```

The exception's message is:

```
com.fasterxml.jackson.databind.util.TokenBuffer cannot be cast to com.fasterxml.jackson.dataformat.xml.ser.ToXmlGenerator (through reference chain: com.ning.billing.recurly.model.Invoice["adjustment"])
```

And this is the relevant part of its stacktrace:

```
java.lang.ClassCastException: com.fasterxml.jackson.databind.util.TokenBuffer cannot be cast to com.fasterxml.jackson.dataformat.xml.ser.ToXmlGenerator
	at com.ning.billing.recurly.model.jackson.RecurlyObjectsSerializer.serialize(RecurlyObjectsSerializer.java:49)
	at com.ning.billing.recurly.model.jackson.RecurlyObjectsSerializer.serialize(RecurlyObjectsSerializer.java:32)
	at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanPropertyWriter.serializeAsField(XmlBeanPropertyWriter.java:144)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
	at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializerBase.serializeFields(XmlBeanSerializerBase.java:135)
	at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializer.serialize(XmlBeanSerializer.java:117)
	at com.fasterxml.jackson.dataformat.xml.ser.XmlSerializerProvider.serializeValue(XmlSerializerProvider.java:92)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2444)
	at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2586)
```

To make it work, I've replaced the `serialize` implementation in `RecurlyObjectsSerializer` with the code below:

```java
@Override
public void serialize(final T values, JsonGenerator jgen, SerializerProvider provider) throws IOException {
	if (values.isEmpty()) {
		jgen.writeStartArray();
		jgen.writeEndArray();
		return;
	}

	final JsonGenerator jsonGenerator = jgen; // Cast as JsonGenerator instead of ToXmlGenerator to prevent crash
	// Nested RecurlyObjects
	if (jsonGenerator.getOutputContext() instanceof JsonWriteContext) {
		((JsonWriteContext) jsonGenerator.getOutputContext()).writeFieldName(elementName);
	}
	boolean firstValue = true;
	for (final U value : values) {
		if (firstValue) {
			if (jgen instanceof ToXmlGenerator) {
				((ToXmlGenerator) jsonGenerator).setNextName(new QName(null, elementName));
			}
		} else {
			jsonGenerator.writeFieldName(elementName);
		}
		firstValue = false;

		jsonGenerator.writeObject(value);
	}
}
```

If it looks fine for you I can make a PR.

**Comment by aaron-suarez** [comment]
@m-revetria I would like to get a PR going for this change. I haven't tried out the code yet, but I don't see any immediate red flags. If you want to go ahead and open the PR, I'll pull down your code and test it out and if it looks good, I'll merge it in.

If for any reason you don't want to do a PR anymore, let me know and I'll open it myself to get this issue closed out.

**Comment by bhelx** [comment]
@m-revetria I have to say, the fact that `RecurlyObject.newXmlMapper()` is exposed as public appears to be more of a convenience to the developers of this library. It's an implementation detail that shouldn't be exposed as part of the API. It's certainly our mistake for exposing it, but I feel like this is on the edge of what we can support. We never intended to support turning Recurly objects into JSON and would prefer people write their own serializers.

Having said that, I think we can get this change in for you if it's a small thing as I'd like to keep you on the main release cycle. There are a couple obstacles here.

1. I don't really understand what it's doing yet. We'd need a little more explanation about what the change is doing so we can support it moving forward.
2. We don't have tests against the multiple versions of Jackson we try to support in the shaded build. We typically mitigate this by never making changes to the xml serialization and deserialization code. Can we be sure this won't break any changes for people with different versions of Jackson?

**Comment by aaron-suarez** [comment]
Closing this issue due to inactivity. Please feel free to re-open with an explanation of what exactly the change is doing and perhaps a test of various versions of Jackson so we can ensure it won't break different versions.
