### ISSUE TITLE
CustomFields not serializable to JsonNode

### ISSUE THREAD

**Issue by jordan-etleap** [killbilling/recurly-java-library#421]
**Describe the bug**

I am trying to use the RecurlyObject XML mapper to write the values to a JsonNode. This seems to work except when there is a CustomFields entity, in which case it yields a `java.lang.ClassCastException: com.ning.billing.recurly.shaded.com.fasterxml.jackson.databind.util.TokenBuffer cannot be cast to com.ning.billing.recurly.shaded.com.fasterxml.jackson.dataformat.xml.ser.ToXmlGenerator` (full stack trace below). 

The error is obtuse, but my understanding is that this is because the serialization protocol is incomplete for `CustomFields`. 

**To Reproduce**

I am trying to serialize an Account entity, but am able to reproduce it directly with just CustomFields  (serializing `CustomField` by itself works)

```
CustomField customField = new CustomField();
customField.setName("name");
customField.setValue("value");
CustomFields customFields = new CustomFields();
customFields.setRecurlyObject(customField);
RecurlyObject.newXmlMapper().valueToTree(customFields); // this throws error
```

**Expected behavior**

I was expecting the CustomFields to be successfully written as a JsonNode.

**Your Environment**

- Which version of this library are you using?  0.103.0
- Which version of java are you using? OpenJDK 8

**Full Stack Trace**
Here is the relevant part of the stack trace I see with production data for serializing an Account that was retrieved using recurly-java-library facilities for fetching data. Unfortunately it looks like it truncated the part of the trace where we are calling the recurly-java-library methods but it should still be illustrative.
```
Caused by: com.ning.billing.recurly.shaded.com.fasterxml.jackson.databind.JsonMappingException: com.ning.billing.recurly.shaded.com.fasterxml.jackson.databind.util.TokenBuffer cannot be cast to com.ning.billing.recurly.shaded.com.fasterxml.jackson.dataformat.xml.ser.ToXmlGenerator (through reference chain: com.ning.billing.recurly.model.Adjustment["account"]->com.ning.billing.recurly.model.Account["custom_field"])
	at com.ning.billing.recurly.shaded.com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.ning.billing.recurly.shaded.com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at com.ning.billing.recurly.shaded.com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:190)
	at com.ning.billing.recurly.shaded.com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:671)
	at com.ning.billing.recurly.shaded.com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializerBase.serializeFields(XmlBeanSerializerBase.java:135)
	at com.ning.billing.recurly.shaded.com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializer.serialize(XmlBeanSerializer.java:117)
	at com.ning.billing.recurly.shaded.com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:575)
	at com.ning.billing.recurly.shaded.com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:663)
	at com.ning.billing.recurly.shaded.com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializerBase.serializeFields(XmlBeanSerializerBase.java:135)
	at com.ning.billing.recurly.shaded.com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializer.serialize(XmlBeanSerializer.java:117)
	at com.ning.billing.recurly.shaded.com.fasterxml.jackson.dataformat.xml.ser.XmlSerializerProvider.serializeValue(XmlSerializerProvider.java:92)
	at com.ning.billing.recurly.shaded.com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2238)
	at com.ning.billing.recurly.shaded.com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2365)
	... 34 common frames omitted
Caused by: java.lang.ClassCastException: com.ning.billing.recurly.shaded.com.fasterxml.jackson.databind.util.TokenBuffer cannot be cast to com.ning.billing.recurly.shaded.com.fasterxml.jackson.dataformat.xml.ser.ToXmlGenerator
	at com.ning.billing.recurly.model.jackson.RecurlyObjectsSerializer.serialize(RecurlyObjectsSerializer.java:49)
	at com.ning.billing.recurly.model.jackson.RecurlyObjectsSerializer.serialize(RecurlyObjectsSerializer.java:32)
	at com.ning.billing.recurly.shaded.com.fasterxml.jackson.dataformat.xml.ser.XmlBeanPropertyWriter.serializeAsField(XmlBeanPropertyWriter.java:144)
	at com.ning.billing.recurly.shaded.com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:663)
	... 43 common frames omitted
```

Thank you in advance for your assistance, and Happy New Years!

**Comment by joannasese** [comment]
@jordan-etleap happy new year! Thanks for reporting. I was able to reproduce the error you're encountering. We'll go ahead and investigate.

**Comment by jordan-etleap** [comment]
Thanks Joanna. Let me know if you have further questions or if there is anything I can do to help.

**Comment by jordan-etleap** [comment]
@joannasese I think I've discovered a solution. It seems that the object `CustomFields` should never have been created. I was able to get it to work by removing the `CustomFields` class and replacing all instances of it with `List<CustomField>` where it occurred. This will allow it to work similarly to other arrays, such as "tax_details" in `Adjustment`. If that seems like an agreeable solution, I will post a PR

**Comment by jordan-etleap** [comment]
It turns out my solution of using `List<CustomField>` doesn't work when there are no custom fields (throws a NullPointerException). At this point, we have decided to upgrade to the V3 version of the API as that returns JSON already. You can close this issue out.

**Comment by joannasese** [comment]
@jordan-etleap good to hear you'll be using v3. We may choose to move forward with fixing this bug nonetheless, but I'll close out this issue.
