### ISSUE TITLE
Invoice fetcher generates JsonMappingException

### ISSUE THREAD

**Issue by fedepia** [killbilling/recurly-java-library#54]
The following code fetches the xml account but the xml mapper raises an error.

```java
    @Category(UnitTest.class)
    @Test
    public void testGetBillingHistory()
    {
    	System.setProperty("recurly.debug", "true");
    	
    	RecurlyClient recurlyClient = new RecurlyClient(API_KEY);
    	recurlyClient.open();
    	
    	try 
    	{
    		Invoices invoices = recurlyClient.getAccountInvoices("1");
    		
    		recurlyClient.close();
    	}
    	catch (Exception e)
    	{
    		e.printStackTrace();
    	}
    }
```

The generated error is:

    WARN : com.ning.billing.recurly.RecurlyClient - Error while calling Recurly
    com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
     at [Source: java.io.StringReader@7aaf8b32; line: 9, column: 27] (through reference chain: com.ning.billing.recurly.model.Invoices["invoice"]->com.ning.billing.recurly.model.Invoice["vat_number"])
    	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
    	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:691)
    	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:46)
    	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
    	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
    	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)

**Comment by bhelx** [comment]
Could not reproduce this. Please update your library to the latest version and let us know if you are still having this problem.
